// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgettoFinale;

#nullable disable

namespace ProgettoFinale.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20241215172144_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("ProgettoFinale.Models.MealRicerca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CountSearch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeRicerca")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("mealsDB");
                });
#pragma warning restore 612, 618
        }
    }
}
